### ISSUE TITLE
VSCode may freeze in a timing of conversion of MS-IME with preview.

### ISSUE THREAD

**Issue by ConquestArrow** [kexi/vscode-uiflow#73]
ある程度の分量（200行～300行）のある UI Flows テキストをプレビューしながら編集していると、IMEの変換のタイミングでVSCodeがフリーズすることがあります。プレビューをしないと発生しません。

VSCode may freeze in a timing of the conversion of IME when I edit it while previewing a UI Flows text with some quantity (200 - 300 lines). It does not occur when I do not preview it.

 - 一度でもプレビューを行うとそれ以降プレビューしていなくても発生するようになります
 - 「`Export PNG`」によるプレビューでも発生することがあります
 - フリーズするとメニュー等の操作はできますがエディタ部分が反応しなくなります
  - その後一定時間後に「ウィンドウから応答がありません」というダイアログが表示されます
 - IME側の不具合を疑い、辞書の修復・OS言語指定などの対処を行ってみましたが改善しませんでした

Environment / 発生環境:

 - VSCode: 1.6.1
 - UiFlow: 0.4.1
 - Windows: 10 pro 64-bit ver. 1607 build 4393.321
 - MS-IME: 10.0.14393.0

**Comment by kexi** [comment]
詳細な報告ありがとうございます 👍 
調査します。

**Comment by kexi** [comment]
@ConquestArrow

I'm releasing v0.4.2 to fix this issue.

**Comment by ConquestArrow** [comment]
Thank you!

ありがとうございました！

**Comment by kexi** [comment]
Thanks for your reporting. :smile:
ご報告いただきありがとうございました。 :smile:
