### ISSUE TITLE
画像エクスポート

### ISSUE THREAD

**Issue by NaomiOsaki** [kexi/vscode-uiflow#94]
とても便利に使わせていただいております。ありがとうございます。画像エクスポートができないのですがgraphvizなどが必要でしょうか？　OSはWindows10です。PNGのDL画面までは表示されますが、パスを指定してEnter を押しても何も起こらずパスの入力欄がリセットされる状態です。

**Comment by kexi** [comment]
ご報告ありがとうございます。
graphvizなどのインストールは不要です。

手元のWindows10では再現できませんでした。
しかしAppVeyorでエクスポートのテストが失敗するようになっていたので、何かあるかもしれません。
他のエクスポートは動作していますでしょうか？

**Comment by NaomiOsaki** [comment]
ご返信をありがとうございます。アンインストール→再インストールし、拡張子はmd, uifどちらも試しましたが、やはりPNG、SVG、DOTも同じ現象でエクスポートができませんでした。
