### ISSUE TITLE
command 'vscode.previewHtml' not found

### ISSUE THREAD

**Issue by future-mano** [kexi/vscode-uiflow#95]
# Einvironmentals 

VS Code Version 1.41.1
Windows_NT x64

# Problem?

An error occurs when installing Uiflow and trying to display images by pressed "Open Preview" icon.

![image](https://user-images.githubusercontent.com/32765876/72122366-fbc50b00-33a0-11ea-9cfc-48d90586c112.png)

But setting "Enable Auto Preview" then success for display.

![image](https://user-images.githubusercontent.com/32765876/72122406-1c8d6080-33a1-11ea-9a88-6321df04be35.png)

![image](https://user-images.githubusercontent.com/32765876/72122412-21eaab00-33a1-11ea-8f83-46d599219e73.png)

**Comment by kexi** [comment]
@future-mano 遅くなって申し訳ございません。Windows 10のバージョンはなんですか？　🥇
